// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func path(name string) templ.SafeURL {
	return templ.SafeURL("/" + name)
}
